#!/bin/sh

set -e

rm -f smallz4cat
gcc -std=c99 -I ../inc smallz4cat.c -o smallz4cat

../decomplz4l_prep/__init__.py ./demo/demo.ihex ./demo/minfo.py
../decomplz4l_prep/phyihex.py ./demo/demo.ihex.lz4l.ihex 0x80000000 0x8000FFFF 0x02000000 0x02000FFF

#sanity check
./smallz4cat lz4_output.bin > decompressed.bin

sha256sum decompressed.bin
sha256sum lz4_input.bin

diff -q decompressed.bin lz4_input.bin
if [ $? -eq 1 ]; then
    echo "ERROR: decompressed file does not match input"
    exit 1
fi
echo "SANITY CHECK PASS"
exit 0
